name: Host Monitor
on:
  schedule:
    - cron: '*/30 * * * *'  # Проверка каждые 30 минут
  workflow_dispatch:        # Ручной запуск

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check host
        id: check
        run: |
          # Проверяем доступность хоста с таймаутом 10 секунд
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 http://chapay.duckdns.org:8123/ || echo "000")
          if [ "$STATUS" -eq 200 ]; then
            echo "result=UP" >> $GITHUB_OUTPUT
            echo "status_code=$STATUS" >> $GITHUB_OUTPUT
          else
            echo "result=DOWN" >> $GITHUB_OUTPUT
            echo "status_code=$STATUS" >> $GITHUB_OUTPUT
          fi

      - name: Send Telegram alert
        if: steps.check.outputs.result == 'DOWN'
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.CHAT_ID }}" \
          -d "text=🚨 ВНИМАНИЕ! Хост http://chapay.duckdns.org:8123/ недоступен!%0AКод статуса: ${{ steps.check.outputs.status_code }}%0AВремя: $(date '+%Y-%m-%d %H:%M:%S')" \
          -d "disable_web_page_preview=true"
