name: Home Assistant Monitor
on:
  schedule:
    - cron: '*/30 * * * *'  # Проверка каждые 30 минут
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check Home Assistant
        id: check
        run: |
          # Пробуем получить ответ от HA с таймаутом 10 секунд
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 20 http://chapay.duckdns.org:8123/ || echo "CURL_ERROR")
          
          # Home Assistant может возвращать 401 (Unauthorized) при работающем сервисе
          if [[ "$RESPONSE" =~ ^(200|401)$ ]]; then
            echo "result=UP" >> $GITHUB_OUTPUT
            echo "status_code=$RESPONSE" >> $GITHUB_OUTPUT
          else
            echo "result=DOWN" >> $GITHUB_OUTPUT
            echo "status_code=$RESPONSE" >> $GITHUB_OUTPUT
          fi

      - name: Send Telegram alert
        if: steps.check.outputs.result == 'DOWN'
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.CHAT_ID }}" \
          -d "text=🚨 ВНИМАНИЕ! Проблема с Home Assistant!%0AАдрес: http://chapay.duckdns.org:8123/%0AКод ответа: ${{ steps.check.outputs.status_code }}%0AВремя: $(date '+%Y-%m-%d %H:%M:%S')%0A%0AПроверьте сервер вручную." \
          -d "disable_web_page_preview=true"
